function z = QuadraticEval2D(p,x,y)
% Function to evaluate the velocity value at a given postion ,using the
% quadratic surface generated by Quadraticfit2D.m

% This is an optimized form of polyval2.m availabe online

x=x(:);
y=y(:);
lx=length(x);
ly=length(y);
lp=length(p);
pts=lx*ly;
y=y*ones(1,lx);
x=ones(ly,1)*x';
x = x(:);
y = y(:);
n=2;
V=zeros(pts,lp);
V(:,1) = ones(pts,1);
ordercolumn=1;
for order = 1:n
    for ordercolumn=ordercolumn+(1:order)
        V(:,ordercolumn) = x.*V(:,ordercolumn-order);
    end
    ordercolumn=ordercolumn+1;
    V(:,ordercolumn) = y.*V(:,ordercolumn-order-1);
end
z=V*p';
z=reshape(z,ly,lx);